// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFI.AccesoADatos;

#nullable disable

namespace TFI.AccesoADatos.Migrations
{
    [DbContext(typeof(IPTNetContext))]
    partial class IPTNetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TFI.Dominio.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<double>("MontoOriginal")
                        .HasColumnType("float");

                    b.Property<int?>("PagoCuotaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrimerVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SegundoVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TercerVencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("Cuotas", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pago_Id")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Pago_Id")
                        .IsUnique()
                        .HasFilter("[Pago_Id] IS NOT NULL");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Indumentaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Indumentarias", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.LineaDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Indumentaria_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Venta_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Indumentaria_Id");

                    b.HasIndex("Venta_Id");

                    b.ToTable("LineasDeVenta", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int?>("Venta_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Venta_Id")
                        .IsUnique()
                        .HasFilter("[Venta_Id] IS NOT NULL");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.PagoCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuotaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedioPago")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Efectivo");

                    b.Property<double>("MontoAbonado")
                        .HasColumnType("float");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Recargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("CuotaId");

                    b.ToTable("PagosCuotas", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CantidadMaxima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("CantidadMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int?>("Indumentaria_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Talle_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Indumentaria_Id");

                    b.HasIndex("Talle_Id");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Talle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Talles", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("TFI.Dominio.Cuota", b =>
                {
                    b.HasOne("TFI.Dominio.Alumno", "Alumno")
                        .WithMany("Cuotas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("TFI.Dominio.Factura", b =>
                {
                    b.HasOne("TFI.Dominio.Pago", null)
                        .WithOne("Factura")
                        .HasForeignKey("TFI.Dominio.Factura", "Pago_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TFI.Dominio.LineaDeVenta", b =>
                {
                    b.HasOne("TFI.Dominio.Indumentaria", "Indumentaria")
                        .WithMany()
                        .HasForeignKey("Indumentaria_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TFI.Dominio.Venta", null)
                        .WithMany("LineaDeVentas")
                        .HasForeignKey("Venta_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Indumentaria");
                });

            modelBuilder.Entity("TFI.Dominio.Pago", b =>
                {
                    b.HasOne("TFI.Dominio.Venta", null)
                        .WithOne("Pago")
                        .HasForeignKey("TFI.Dominio.Pago", "Venta_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TFI.Dominio.PagoCuota", b =>
                {
                    b.HasOne("TFI.Dominio.Cuota", "Cuota")
                        .WithMany()
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuota");
                });

            modelBuilder.Entity("TFI.Dominio.Stock", b =>
                {
                    b.HasOne("TFI.Dominio.Indumentaria", "Indumentaria")
                        .WithMany()
                        .HasForeignKey("Indumentaria_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TFI.Dominio.Talle", "Talle")
                        .WithMany()
                        .HasForeignKey("Talle_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Indumentaria");

                    b.Navigation("Talle");
                });

            modelBuilder.Entity("TFI.Dominio.Alumno", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("TFI.Dominio.Pago", b =>
                {
                    b.Navigation("Factura");
                });

            modelBuilder.Entity("TFI.Dominio.Venta", b =>
                {
                    b.Navigation("LineaDeVentas");

                    b.Navigation("Pago");
                });
#pragma warning restore 612, 618
        }
    }
}
